// tsc-ui-dashboard/src/App.svelte
<!-- App.svelte -->
<script>
    import Sidebar from './Sidebar.svelte';
    import {onMount} from 'svelte';
    import ProjectStatus from "./ProjectStatus.svelte";
    import Diagnostics from "./Diagnostics.svelte";
    import Navbar from "./Navbar.svelte";
    import { status } from './store';

    onMount(() => {
        const id = window.setInterval(status.getStatus, 500);
        status.getStatus();
        return () => {
            window.clearInterval(id);
        };
    });
</script>

<Navbar />

<div class="flex flex-col md:flex-row">
    <Sidebar />
    <Diagnostics />
    <ProjectStatus />
</div>

// preact-snowpack/src/App.tsx
import {h} from 'preact';
import {useEffect} from 'preact/hooks';
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";
import Diagnostics from "./Diagnostics";
import ProjectStatus from "./ProjectStatus";
import {useStore} from "./store/store";

function App() {
    const {dispatch} = useStore('messages');
    useEffect(() => {
        dispatch('load');
    }, []);
    return (
        <div>
            <Navbar/>

            <div class="flex flex-col md:flex-row">
                <Sidebar/>
                <Diagnostics />
                <ProjectStatus/>
            </div>

        </div>
    );
}

export default App;
